
name: My workflow
on: [push]

jobs:
  PetersJob:
    runs-on: ubuntu-latest
    steps:
      - run: echo This is a step within a job.
      - run: uname -a
      - uses: actions/checkout@v7.0.0
      - run: find .
      - run: docker build -t test:latest .