
name: My workflow
on: [push]

jobs:
  PetersJob:
    runs-on: ubuntu-latest
    steps:
      - run: echo This is a step within a job on ${{github.ref_name}}
      - run: uname -a
      - env:
          MY_ENV_VAR: "This is an env var"
        run: echo $MY_ENV_VAR